baseURL = "https://yamacraft.github.io/note/"
title = "山田航空ネットワーク3rd"
languageCode = "ja-jp"
theme = "mediumish"

hasCJKLanguage = true
enableEmoji = true
googleAnalytics = "G-WN2EJQSS9T"

copyright = "yamacraft"

[params]
author = "yamacraft"
description="yamacraftの雑記"

license = "CC BY 4.0"
licenseURL = "https://creativecommons.org/licenses/by/4.0/deed.ja"

images = ["image/ogp.png"]
customCss = ["css/note.css"]
